### ISSUE TITLE
java.lang.String cannot be cast to netscape.javascript.JSObject

### ISSUE THREAD

**Issue by ElectronicManuel** [Lusito/web-ext-translator#15]
Hey,
Thanks for fixing #14 
When I run `wet` now an empty window with a dark background opens with the following console output:
```
PS E:\Browser_Extensions\VideoSyncer\src> java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
PS E:\Browser_Extensions\VideoSyncer\src> npm view -g web-ext-translator version
2.0.5
PS E:\Browser_Extensions\VideoSyncer\src> wet
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: java.lang.String cannot be cast to netscape.javascript.JSObject
        at info.lusito.web_ext_translator.Main.onLoad(Main.java:31)
        at info.lusito.web_ext_translator.Main.lambda$start$0(Main.java:54)
        at info.lusito.web_ext_translator.Main$$Lambda$92/1599764416.changed(Unknown Source)
        at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
        at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
        at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1226)
        at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1337)
        at javafx.scene.web.WebEngine$LoadWorker.access$1100(WebEngine.java:1219)
        at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1206)
        at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2387)
        at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2231)
        at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:819)
        at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$92(URLLoader.java:810)
        at com.sun.webkit.network.URLLoader$$Lambda$99/42217992.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl$$Lambda$47/771644126.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl$$Lambda$46/501263526.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$141(WinApplication.java:102)
        at com.sun.glass.ui.win.WinApplication$$Lambda$37/96639997.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Lusito** [comment]
I'm actually not sure why that code would return a string instead of a JSOjbect on your machine.
Could you try updating your Java version? Maybe the code only works with a newer version.
I'm running Version 1.8.0.151-b12 on this machine and it works fine.

You can get the latest JRE for Java 8 here: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Thanks for your patience.

**Comment by ElectronicManuel** [comment]
I changed my java version to `1.8.0_151-b12` and it did the trick!

```
PS E:\Browser_Extensions\VideoSyncer\src> java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
PS E:\Browser_Extensions\VideoSyncer\src> npm view -g web-ext-translator version
2.0.5
PS E:\Browser_Extensions\VideoSyncer\src> wet
```
